"""IsaacLab-free benchmark episode schema.

The schema is intentionally small. Backends can bind it to a concrete IsaacLab
env, while scoring and dataset conversion can use it without importing IsaacLab.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from typing import Any

XYZ = tuple[float, float, float]
QUAT_WXYZ = tuple[float, float, float, float]


def _float3(value: Any, *, name: str) -> XYZ:
    if not isinstance(value, list | tuple) or len(value) < 3:
        raise ValueError(f"{name} must be a 3-element sequence, got {value!r}")
    return float(value[0]), float(value[1]), float(value[2])


def _quat_wxyz(value: Any, *, name: str) -> QUAT_WXYZ:
    if not isinstance(value, list | tuple) or len(value) < 4:
        raise ValueError(f"{name} must be a 4-element sequence, got {value!r}")
    return float(value[0]), float(value[1]), float(value[2]), float(value[3])


@dataclass(frozen=True)
class Pose3D:
    """World pose using xyz position and wxyz quaternion."""

    position: XYZ
    orientation_wxyz: QUAT_WXYZ = (1.0, 0.0, 0.0, 0.0)

    def to_dict(self) -> dict[str, Any]:
        return {
            "position": list(self.position),
            "orientation_wxyz": list(self.orientation_wxyz),
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> Pose3D:
        return cls(
            position=_float3(payload.get("position"), name="pose.position"),
            orientation_wxyz=_quat_wxyz(
                payload.get("orientation_wxyz", payload.get("orientation", (1.0, 0.0, 0.0, 0.0))),
                name="pose.orientation_wxyz",
            ),
        )

    @classmethod
    def from_xy_yaw(cls, x: float, y: float, z: float = 0.0, yaw_rad: float = 0.0) -> Pose3D:
        half_yaw = float(yaw_rad) * 0.5
        return cls(
            position=(float(x), float(y), float(z)),
            orientation_wxyz=(math.cos(half_yaw), 0.0, 0.0, math.sin(half_yaw)),
        )


@dataclass(frozen=True)
class SceneSpec:
    """Scene reference for a benchmark episode.

    Two asset fields, because published and resolved are different facts.
    ``asset`` is what the dataset ships: a *relative* ``<dataset>/<scene_id>/<basename>``
    path that only means something against a scene root the user supplies.
    ``asset_path`` is the resolved location on this machine, which is what a
    backend can actually open. ``insight_bench.vln_runtime.episodes.scenes``
    turns the first into the second, and fails closed when it cannot.

    Both are read on parse. Records generated by the converters carry
    ``asset_path`` and nothing else; the published objnav files carry ``asset``
    and nothing else, and reading only ``asset_path`` silently dropped every
    one of them -- an episode with no scene, parsed without complaint.
    """

    scene_id: str
    asset_path: str | None = None
    asset: str | None = None
    scene_type: str = "unknown"
    dataset: str | None = None
    units_in_meters: float = 1.0
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "scene_id": self.scene_id,
            "asset_path": self.asset_path,
            "asset": self.asset,
            "scene_type": self.scene_type,
            "dataset": self.dataset,
            "units_in_meters": self.units_in_meters,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> SceneSpec:
        return cls(
            scene_id=str(payload["scene_id"]),
            asset_path=None
            if payload.get("asset_path") is None
            else str(payload.get("asset_path")),
            asset=None if payload.get("asset") is None else str(payload.get("asset")),
            scene_type=str(payload.get("scene_type", "unknown")),
            dataset=None if payload.get("dataset") is None else str(payload.get("dataset")),
            units_in_meters=float(payload.get("units_in_meters", 1.0)),
            metadata=dict(payload.get("metadata") or {}),
        )


@dataclass(frozen=True)
class RobotSpec:
    """Embodiment/backend hint for an episode."""

    robot_id: str = "free_camera"
    embodiment: str = "free_camera"
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "robot_id": self.robot_id,
            "embodiment": self.embodiment,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any] | None) -> RobotSpec:
        if payload is None:
            return cls()
        return cls(
            robot_id=str(payload.get("robot_id", "free_camera")),
            embodiment=str(payload.get("embodiment", "free_camera")),
            metadata=dict(payload.get("metadata") or {}),
        )


@dataclass(frozen=True)
class SubtaskSpec:
    """Ordered VLN subtask description.

    The target fields are deliberately generic so adapters can preserve dataset
    specifics without needing a new Python type for every benchmark.
    """

    type: str
    target_id: str | None = None
    target_position: XYZ | None = None
    radius_m: float | None = None
    instruction: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": self.type,
            "target_id": self.target_id,
            "target_position": None if self.target_position is None else list(self.target_position),
            "radius_m": self.radius_m,
            "instruction": self.instruction,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> SubtaskSpec:
        target_position = payload.get("target_position")
        return cls(
            type=str(payload["type"]),
            target_id=None if payload.get("target_id") is None else str(payload.get("target_id")),
            target_position=None
            if target_position is None
            else _float3(target_position, name="subtask.target_position"),
            radius_m=None if payload.get("radius_m") is None else float(payload.get("radius_m")),
            instruction=None
            if payload.get("instruction") is None
            else str(payload.get("instruction")),
            metadata=dict(payload.get("metadata") or {}),
        )


_EPISODE_ID_RE = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._-]*\Z")


def validate_episode_id(value: Any) -> str:
    """Accept an episode id only if it is safe to use as a single filesystem path segment.

    Episode ids name directories -- ``<artifact_dir>/<episode_id>/trace.json`` -- and datasets are
    user-supplied by design for the gated suite. An id of ``../../x`` or ``/etc/cron.d/x`` would
    otherwise let a dataset choose where a run writes.

    A slug is stricter than "does not escape": no separators, no leading dot, no empty string. The
    point is that an id which is not a plain path segment never reaches path handling at all,
    rather than being sanitised into something the trace no longer matches.
    """
    text = str(value)
    if not _EPISODE_ID_RE.match(text):
        raise ValueError(
            f"unsafe episode_id {text!r}: expected a slug of letters, digits, '.', '_' or '-' "
            f"starting with a letter or digit -- ids name a directory under the artifact root"
        )
    return text


@dataclass(frozen=True)
class EpisodeSpec:
    """Stable benchmark input independent of a concrete simulator backend."""

    episode_id: str
    instruction: str
    scene: SceneSpec
    start_pose: Pose3D
    goal_position: XYZ | None = None
    goal_radius_m: float = 2.0
    robot: RobotSpec = field(default_factory=RobotSpec)
    subtasks: list[SubtaskSpec] = field(default_factory=list)
    reference_path: list[XYZ] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "episode_id": self.episode_id,
            "instruction": self.instruction,
            "scene": self.scene.to_dict(),
            "start_pose": self.start_pose.to_dict(),
            "goal_position": None if self.goal_position is None else list(self.goal_position),
            "goal_radius_m": self.goal_radius_m,
            "robot": self.robot.to_dict(),
            "subtasks": [subtask.to_dict() for subtask in self.subtasks],
            "reference_path": [list(point) for point in self.reference_path],
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> EpisodeSpec:
        goal_position = payload.get("goal_position")
        return cls(
            episode_id=validate_episode_id(payload["episode_id"]),
            instruction=str(payload.get("instruction", "")),
            scene=SceneSpec.from_dict(payload["scene"]),
            start_pose=Pose3D.from_dict(payload["start_pose"]),
            goal_position=None
            if goal_position is None
            else _float3(goal_position, name="episode.goal_position"),
            goal_radius_m=float(payload.get("goal_radius_m", 2.0)),
            robot=RobotSpec.from_dict(payload.get("robot")),
            subtasks=[SubtaskSpec.from_dict(item) for item in payload.get("subtasks", [])],
            reference_path=[
                _float3(point, name="episode.reference_path[]")
                for point in payload.get("reference_path", [])
            ],
            metadata=dict(payload.get("metadata") or {}),
        )
